### ISSUE TITLE
Kde se chytají výjimky?

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#10]
https://github.com/RadStr/Music-Keyboard/blob/de698d5e6ce9e0bcfe825450fcb83fc38fa86386/Keyboard.cpp#L60

Kde se chytají výjimky?
Tohle není preferovaný způsob, jak vyhazovat výjimky. Není nutné dynamicky alokovat... Kdo ji bude dealokovat? Stačí vyhodit klasicky alokovanou na stacku.

**Comment by RadStr** [comment]
Změněno. Výjimky vyhazovány na stacku místo na haldě. 
Opraveno: Kritické výjimky (ty které značí, že je něco špatně s programem - třeba se dostaneme do větve, kde nemáme být, nebo viz. tato označená v konstruktoru) se vyhazují ven a odchytávají v mainu, následně se program ukončí.
Ostatní výjimky (např. typu špatný formát config souboru) se pouze zalogují a program běží dál.
