### ISSUE TITLE
Musí být alokované dynamicky?

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#11]
https://github.com/RadStr/Music-Keyboard/blob/de698d5e6ce9e0bcfe825450fcb83fc38fa86386/Keyboard.cpp#L63

**Comment by RadStr** [comment]
S tím jak jsem to naprogramoval, tak ano. Používám tam proměnnou textboxWithFocus, do které si vždy uložim textbox, který by momentálně měl zpracovávat příchozí eventy, případně nullptr, pokud žádný textbox nebyl vybrán uživatelem.
Dalo by se to dělat i bez dynamické alokace, ale takhle to je jednodušší a podle mě i přehlednější.
Ale audioPlayingLabel tento problém řešit nemusel, takže ten jsem změnil, aby už nebyl alokovaný dynamicky.

**Comment by fan1x** [comment]
> S tím jak jsem to naprogramoval, tak ano. Používám tam proměnnou textboxWithFocus, do které si vždy uložim textbox, který by momentálně měl zpracovávat příchozí eventy, případně nullptr, pokud žádný textbox nebyl vybrán uživatelem.
Jsou dvě rozdílné věci. Dynamický alokované věci a vzít si pointer/adresu na daný objekt. Tedy, ikdyž věc není dynamicky alokovaná, můžeš na ní mít namířený pointer/referenci. 
Takže nemusíš alokovat dynamicky a do `textboxWithFocus` přiřadit adresu proměnně.

Něco podobného jako:
```
if (newFocus) {
	clickedTextbox->hasFocus = true;
	this->textboxWithFocus = &clickedTextbox;
}
else {
	this->textboxWithFocus = nullptr;
}

--> 

if (newFocus) {
	clickedTextbox->hasFocus = true;
	this->textboxWithFocus = &clickedTextbox;
}
else {
	this->textboxWithFocus = nullptr;
}
```

**Comment by RadStr** [comment]
Máš pravdu, nějak mi to nedošlo. 
Změněno.

**Comment by fan1x** [comment]
Změnit na všech místech:
https://github.com/RadStr/Music-Keyboard/blob/b5677b0de7d0609152320f5d62da22efb45ad057/Keyboard.cpp#L1398

**Comment by RadStr** [comment]
Změněno pro proměnnou audioSpec ve třídě Keyboard https://github.com/RadStr/Music-Keyboard/blob/7249b17735f76b4eadce361794fbca2a5a4dc7bb/Keyboard.h#L48-L49 a pak https://github.com/RadStr/Music-Keyboard/blob/7249b17735f76b4eadce361794fbca2a5a4dc7bb/Key.cpp#L49 a teď nevim jestli ještě někde jinde. 

Ty pole: https://github.com/RadStr/Music-Keyboard/blob/b5677b0de7d0609152320f5d62da22efb45ad057/Keyboard.cpp#L1398-L1404 podle mě nejdou bez dynamické alokace, protože počet kanálů nemusí být vždy konstanta. To závisí na tom, jestli se povede otevřít audio device s požadovaným počtem kanálů, viz. https://github.com/RadStr/Music-Keyboard/blob/ad7677176910d62f722333067b02f6c96ece1f11/Keyboard.cpp#L106
Teď jsem změnil ještě poslední argument metody, abych explicitně sdělil, že umožňuju změnit počet kanálů. 
Takže maximálně můžu použít vector.

**Comment by fan1x** [comment]
> Takže maximálně můžu použít vector.

To jsem myslel, sorry, blbě jsem se vyjádřil :) Obecně, pokud to není performance critical, tak se vyhýbat raw alokacím `std::vector + reserve/resize` je dostatečný

**Comment by RadStr** [comment]
Všechna pole změněna na vektory, kromě těch které rovnou přiřazuji do SDL_AudioCVT struktury jako buffer, u nich vytvářim kvůli zpětné kompatibilitě jen pole.
A pak tam už jen zůstaly dynamické alokace, které jsou vyžadované při práci s SDL knihovnou (renderer, textury, atd.)
