### ISSUE TITLE
Být konzistantní

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#12]
https://github.com/RadStr/Music-Keyboard/blob/de698d5e6ce9e0bcfe825450fcb83fc38fa86386/Keyboard.cpp#L134

Proč je volání funkce takhle zarovnané? Přesahuje nějaký limit počtu znaků na řádek? Pokud ano, proč to jinde nevadí?

**Comment by RadStr** [comment]
Žádný limit to nepřesahovalo, nejspíše jsem to tak zarovnal, protože jsem to tak viděl psané v dokumentaci.
Opraveny další podobné výskyty tak, abych zarovnával jen když to překročilo počet znaků na řádku (180 znaků).
Výjimkou jsou podmíněné příkazy, tam zalamuji řádky, tak aby na jedné řádce byly maximálně 3 podmínky.
