### ISSUE TITLE
Špatná dealokace paměti

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#13]
https://github.com/RadStr/Music-Keyboard/blob/de698d5e6ce9e0bcfe825450fcb83fc38fa86386/Keyboard.cpp#L1404

Špatná dealokace paměti, více zde: https://en.cppreference.com/w/cpp/memory/c/free

**Comment by RadStr** [comment]
Opraveno. new dealokuji pomocí delete. new[] pomocí delete[]
