### ISSUE TITLE
Vyhýbej se C&P kodů

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#14]
https://github.com/RadStr/Music-Keyboard/blob/de698d5e6ce9e0bcfe825450fcb83fc38fa86386/Keyboard.cpp#L2035

Snaž se co nejvíc vyhnout kopírování a nahraď to voláním funkce. 
Je to někdy použité s parametrem `draw==false`?
- Pokud ne, tak to odstraň a můžeš to napsat jednoduššeji...
- Pokud ano, testuješ to někde, že to opravdu funguje tak jak má?

**Comment by RadStr** [comment]
Volá se s oběma parametry. Když má parametr draw==false, tak metoda zkusí jestli se současným fontem vejdou popisky ke klávesám. Pokud ne (tedy currY < 0), tak vrátíme currY a víme, že potřebujeme zmenšit font.
Takže s parametrem draw == false se postupně voláme na všechny klávesy, dokud nenajdeme největší font, který můžeme vykreslit.
A pak se postupně zavoláme s parametrem draw == true a s fontem, který jsme našli, abychom klávesy vykreslili.

Mělo by to fungovat tak jak má vzhledem k tomu, že mi to popisky ke klávesám vykresluje správně.
(Popisky ke klávesám = číslo klávesy + ovládání)

Možná existuje nějaký lepší způsob jak to dělat, ale doteď mě nenapadl.

**Comment by fan1x** [comment]
Omlouvám se, jsem přehlédl to druhé volání...

No, ono to hodně souvisí s #25, kdybys například udělal pro každou klávesu vlastní třídu + virtuální metody, tak ti to hodně ulehčí práci a bude hezčí kód.
Máš totiž mraky kláves (keys), které dělají to samé akorát je tam drobný rozdíl (jiný název, ...)
