### ISSUE TITLE
Není nutné to mít za každou cenu v konzoli, můžeš přiložit i .sln projekt, aby se to dalo otevřít ve VS inteligentně

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#16]
https://github.com/RadStr/Music-Keyboard/blob/de698d5e6ce9e0bcfe825450fcb83fc38fa86386/VS_CMD_COMPILATION.txt#L1

**Comment by RadStr** [comment]
Přiložil jsem .sln projekt do repository, ale je možné, že to nenalezne potřebné knihovny. Takže je stále preferovaný způsob překladu přes konzoli.

**Comment by fan1x** [comment]
Jojo, pořád to nemůže najít potřebné knihovny. Navíc, jsi přiložil i tvoje *.user soubory, které nejsou potřeba... 
Ideální je vždycky pogooglit, co je potřeba dávat do GITu pro dané prostředí a zkusit to vycloonovat někde vedle v adresáři. 

Jak to vyvíjíš, když ti to tedy nefunguje v VS solution?

**Comment by RadStr** [comment]
Vyvíjím to ve VS akorát když zkopíruju .sln projekt, tak už se nezkopírují ty potřebná nastavení.
Tady je návod, když jsem to sestavoval ve svém VS:
Jít do Projekt->Vlastnosti (Project->Properties) a tam:
{a} C++ general->Additional include directories  a přidám tam include adresář
{b} Linker->General->Additional library directories->lib adresář
{c} Linker->Input->Additional dependencies  a tam přidám SDL2.lib a pak na nový řádek SDL2main.lib
{d} Linker->System->Subsystem a vyberu /SUBSYSTEM:WINDOWS

**Comment by fan1x** [comment]
No, protoze ty nastaveni jsou ulozene v *.vcxproj. Zkus si to utevrit napriklad v notepadu, neni to zadna black magic :)

**Comment by RadStr** [comment]
To jsem nevěděl, díky. Teď už jsem to změnil, aby cesty v *.vcxproj k souborům knihovny byly relativní a ne absolutní, takže už by to mělo fungovat správně.

**Comment by fan1x** [comment]
Pořád to nefunguje... Pořád to nenajde headery pro SDL.h :( 
```
1>------ Rebuild All started: Project: CppKlavesyZapProgram, Configuration: Debug x64 ------
1>Key.cpp
1>d:\projects\_students\cpp\music-keyboard\key.h(4): fatal error C1083: Cannot open include file: 'SDL.h': No such file or directory
1>Keyboard.cpp
1>d:\projects\_students\cpp\music-keyboard\main.h(4): fatal error C1083: Cannot open include file: 'SDL.h': No such file or directory
1>KeySetWindow.cpp
1>d:\projects\_students\cpp\music-keyboard\main.h(4): fatal error C1083: Cannot open include file: 'SDL.h': No such file or directory
1>Main.cpp
1>d:\projects\_students\cpp\music-keyboard\key.h(4): fatal error C1083: Cannot open include file: 'SDL.h': No such file or directory
1>Textbox.cpp
1>d:\projects\_students\cpp\music-keyboard\key.h(4): fatal error C1083: Cannot open include file: 'SDL.h': No such file or directory
1>Generating Code...
1>Done building project "CppKlavesyZapProgram.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

```

**Comment by RadStr** [comment]
To už je snad způsobené jen tím, že tam mám soubory z knihovny jen pro platformu x86.
Už se mi nepovedlo najít, jak VS donutit, aby při zapnutí kompilovalo pro platformu x86.
Takže to je nutné manuálně přepnout před kompilací.

**Comment by fan1x** [comment]
Aha... to mě nenapadlo :D Každopádně, jde to tam taky. Nahoře, jak máš roletku platforms, tak můžeš vybrat nastavení pro všechny platformy... :)
Jinak, v dnešní době bych už automaticky používal x64, pokud pro to není nějaký dobrý důvod.
