### ISSUE TITLE
Používat unsigned typy pokud to má smysl

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#17]
Např:
https://github.com/RadStr/Music-Keyboard/blob/de698d5e6ce9e0bcfe825450fcb83fc38fa86386/Textbox.h#L16

Může být velikost někdy záporná, pokud ne, tak by to měl být `size_t` nebo `unsigned`

**Comment by RadStr** [comment]
Nemůže být záporná, takže změněno na size_t. Dál změněny inty na size_t v nějakých for cyklech, kde jsem na to zapomněl. A změněna proměnná keyCount (udává současný počet kláves na klávesách) z intu na size_t.
