### ISSUE TITLE
Odstranit nefunkční kód

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#18]
https://github.com/RadStr/Music-Keyboard/blob/de698d5e6ce9e0bcfe825450fcb83fc38fa86386/Main.cpp#L34

Nedávat do masteru nefunkční kód. Mít to například v experimentální větvy. Špatně se kód prochází/čte

**Comment by RadStr** [comment]
Odstraněno toto makro společně s kódem k němu. Dál odstraněny deprecated metody.
