### ISSUE TITLE
Udělat hezčí logger (není potřeba nutně opravovat) 

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#24]
Je to na hraně, nemusíš to asi nutně opravovat...

https://github.com/RadStr/Music-Keyboard/blob/e56c89d7b9be7f1dda5bf60cb022e70066b19567/Main.h#L19

Colours nejsou úplně proměnné, ale konstanty.
Lepší by bylo použít například singleton pattern pro logger 😉

**Comment by RadStr** [comment]
Změněno:
Logger jako singleton
konstanty v GlobalConstants

**Comment by fan1x** [comment]
super, jen tohle není moc doporučený způsob jak dělat singleton v C++ (zkus pogooglit), ale to nevad9 ;)
