### ISSUE TITLE
Udělat program lépe objektově

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#25]
Například: https://github.com/RadStr/Music-Keyboard/blob/e56c89d7b9be7f1dda5bf60cb022e70066b19567/Keyboard.cpp#L231

Proč to není pomocí virtuálních metod a dědičnosti? Kdy jindy ji použít 😄

**Comment by RadStr** [comment]
Změněno.
Nyní mají virtuální metodu, kterou zavolám na textboxu s focusem, která provede odpovídající akce.
Ještě přidaná virtuální metoda drawTextbox.

K těm keys. Moc netuším, jak to udělat.
Mě napadlo mít třídu Key a od ní budou dědit třídy BlackKey WhiteKey RecordKey. Kde Key bude obsahovat virtuální metodu draw, tohle zpřehlední vykreslování samotných kláves.
A ty labely bych mohl řešit tak, že u každého Key si budu pamatovat ty labely přímo jako stringy (třeba odděleny mezerami ve stringu nebo ve vectoru postupně všechny). A pak už přes to jen nějak přeiteruju a na každou zavolám ten 1 kód, tím se zbavím toho copy paste:
`currY = f(key, currY, keyLabel, GlobalConstants::WHITE, font, widthTolerance, this->renderer, this->whiteKeyWidth, this->textures);`
`                   if (!draw) {
			if (currY < 0) {
				return currY;
			}
		}`

No ale nic jiného mě nenapadlo, třeba něco ve smyslu, že bych měl pro každý modifikátor (SHIFT, CTRL {levý, pravý, oba}, NUM, CAPS) 1 třídu dědící od keys, tak těch tříd bude pak strašně moc vzhledem k tomu, že modifikátory můžu libovolně kombinovat a vynechávat.

Ještě jsem to neimplementoval, protože si nejsem jistý, jestli je to moje řešení přes stringy, co sis představoval.

**Comment by fan1x** [comment]
Teď jsem ztratil referenci o jakém kódu se bavíš... Můžeš to kdyžtak ještě přiblížit?
Každopádně, stringové operace jsou obecně drahé, takže řešení typy "budu pamatovat ty labely přímo jako stringy (třeba odděleny mezerami ve stringu" určitě není dobré na 99.9% problémů :)

**Comment by RadStr** [comment]
Jojo to vim, že intenzivně pracovat se stringy není dobrý nápad. Ta verze s vectorem by byla samozřejmě efektivnější.
Mluvim o kódu z [#14 ](url) Tedy o kódu https://github.com/RadStr/Music-Keyboard/blob/555b48872b5563891bdfa38bc5b6aae05dff2028/Keyboard.cpp#L2158-L2159

**Comment by fan1x** [comment]
Jsem v pohodě s tím, jak to je :) Byl by potřeba mnohem větší refactoring.
