### ISSUE TITLE
Kod by měl být bez zakomentovaného kódu

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#27]
https://github.com/RadStr/Music-Keyboard/blob/b5677b0de7d0609152320f5d62da22efb45ad057/Keyboard.cpp#L170

Program by mel byt bez zakomentovanych kusu kodu. Pokud chces mit nekde nejaky experimentalni kod, muzes is udelat branch v GITu treba, ale tohle by mel byt cisty pekny kod :)

**Comment by RadStr** [comment]
Odstraněn zakomentovaný kód z main branche, verze s ním je v branchi RadStr-Experimental-main.
