### ISSUE TITLE
Zkusit rozdělit Keybord.cpp

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#32]
Rozdělit ten soubor, není není to moc čitelné, když to má ~3k řádek

**Comment by RadStr** [comment]
Rozdělil jsem ho na soubory KeyboardAudio.cpp KeyboardDraw.cpp KeyboardInit.cpp KeyboardMain.cpp KeyboardSet.cpp. Ale bohužel to je stále 1 třída Keyboard, akorát ve více souborech. Ale rozdělení do více souborů a hlavně rozdělení na oddíly viz.
https://github.com/RadStr/Music-Keyboard/blob/bd613c49fd71590c01ec0a20afcfda58f41875a0/Keyboard.h#L201
by mělo pomoc v orientaci.

**Comment by fan1x** [comment]
Rozdělit do více souborů, ikdyž je to jedna třída je ok. Ideální by bylo i podrozdělit do více podtříd, ale ne vždy to jde.
