### ISSUE TITLE
Zkusit zkompilovat i s pomocí nějakého jiného překladače

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#5]
https://github.com/RadStr/Music-Keyboard/blob/de698d5e6ce9e0bcfe825450fcb83fc38fa86386/Cpp-Dokumentace-Strycek.tex#L18

To že nemáš nainstalovaný jiný překladač není moc validní argument :) Zkus nainstalovat nějaký jiný překladač a zkus to zkompilovat (GCC, Clang, ...)

**Comment by RadStr** [comment]
Zkusil jsem zkompilovat pomocí GCC (MingGW). Nakonec se mi to na něm povedlo zkompilovat i odladit. Ale návod na kompilaci mi přijde zbytečné psát, vzhledem k tomu, že jsem měl s kompilací mnohem víc problémů než ve VS. (např. #include<filesystem> je problémové pro GCC, dále exceptiony nemohou dostávat string jako parametr, problémy s definicemi constexpr, atd.). Navíc vyžaduje jiné linker soubory.

**Comment by fan1x** [comment]
> např. #include je problémové pro GCC
Co tím myslíš?

> dále exceptiony nemohou dostávat string jako parametr
To je divné... Kde je to v kódu?

Proč jsem chtěl, abys zkusil jiný překladač je ten, že GCC je v defaultu víc striktní a navíc, máš potom jistotu, že píšeš C++ podle standardu. Každý překladač si přidává nějakou podporu navíc, ale tu většinou nechceš používat (nebo aspoň vědět, že je to compiler extension)

**Comment by RadStr** [comment]
> např. #include je problémové pro GCC
Co tím myslíš?

Moje chyba, myslel jsem #include \<filesystem\>. Nepomohlo například ani toto: https://stackoverflow.com/questions/39231363/fatal-error-filesystem-no-such-file-or-directory 

> dále exceptiony nemohou dostávat string jako parametr

ERROR: Keyboard.cpp:1229:73: error: no matching function for call to 'std::exception::exception(const char [48])'
   throw std::exception("Button unpressed more times than it was pressed");

Teď už vidím proč jsem k tomu #include nic nenapsal, je to tím, že to bylo uzavřeno ve \<\> a to se tu chová jako nějaké speciální znaky

**Comment by fan1x** [comment]
> ERROR: Keyboard.cpp:1229:73: error: no matching function for call to 'std::exception::exception(const char [48])'
throw std::exception("Button unpressed more times than it was pressed");

Aha... tak on tam ten konstruktor opravdu není. Je to proto, protože je to base class pro všechny další exceptions (https://en.cppreference.com/w/cpp/error/exception). Buď používej ty a nebo si vytvoř vlastní, pokud nelze použít již standardní. 

> Moje chyba, myslel jsem #include <filesystem>. Nepomohlo například ani toto: 

Co používáš za GCC? V novém by to mělo fungovat (minimálně jako experimental)... (to je kvůli tomu MinGW asi máš 6.1?)  Můžeš zkusit jště Clang...
Každopádně, tohle už nemusíš řešit. Ale je dobré umět pracovat s jiným překladačem než VS ;)

**Comment by RadStr** [comment]
Změnil jsem to, aby to vyhazovalo specifičtější výjimky. Viz.
https://github.com/RadStr/Music-Keyboard/blob/bd613c49fd71590c01ec0a20afcfda58f41875a0/KeyboardInit.cpp#L65
https://github.com/RadStr/Music-Keyboard/blob/bd613c49fd71590c01ec0a20afcfda58f41875a0/KeyboardMain.cpp#L270
https://github.com/RadStr/Music-Keyboard/blob/bd613c49fd71590c01ec0a20afcfda58f41875a0/KeyboardMain.cpp#L502

Kompiloval jsem pomocí minGW 6.3.0
