### ISSUE TITLE
Program nelze spustit 

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#6]
https://github.com/RadStr/Music-Keyboard/blob/de698d5e6ce9e0bcfe825450fcb83fc38fa86386/VS_CMD_COMPILATION.txt#L1

Program jsem zkompiloval přesně podle návodu (na Win10 + VS2017), kompilace proběhne úspěšně. Poté zkusím spustit zkompilovaný program, zobrazí se prázdné okno a to po 1s zmizí. 

Je k dispozici nějaký log, ze kterého se dá poznat v čem je problém? Můj soukromý tip je, že bude nějaký problém s knihovnami?

**Comment by RadStr** [comment]
Přidal jsem log. (Loguje se do souboru LOGGER.txt). Ale podle mě nebude potřeba, viz. dále.

Po opravě ostatních issues jsem zkusil program přeložit podle návodu v dokumentaci a tentokrát jsem měl stejný problém jako ty. (Při první odevzdané verzi mi program ale šel normálně).

Hlavní problém byl v tom, že v konstruktoru jsem zapomněl inicializovat proměnnou keys na nullptr a tím pádem jsem pak později zvolil špatnou if větev, kde se proměnná měla inicializovat (keys = new Key[]), tedy jsem pokračoval dál s tím, že keys ukazovalo někam do paměti, která mi nepatřila.

Po přeložení v GCC se objevilo pár dalších problémů v práci s knihovnou. A to, že jsem uvolňoval textury textů dřív než jsem měl, v případě textů u kláves jsem to vyřešil tak, že jsem přidal vektor, kam jsem je postupně přidal a uvolnil až když jsem měl.
U textboxů jsem měl stejný problém, tak ten jsem vyřešil, tak, že si pamatuju poslední 2 textury a vždy vymažu tu, která se už nepoužívá.

Předčasné uvolňování textur mělo za následek nesprávné vykreslování textů, ale jinak program běžel tak, jak by měl.

**Comment by fan1x** [comment]
Jojo, už se mi ho podařilo spustit
