### ISSUE TITLE
Proč používat makra místo konstant?

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#7]
https://github.com/RadStr/Music-Keyboard/blob/de698d5e6ce9e0bcfe825450fcb83fc38fa86386/Keyboard.h#L21

**Comment by RadStr** [comment]
Když jsem to psal, tak mě to asi ani jako konstantu dát nenapadlo.
Takže změněno. Nechal jsem tam jen 2 makra. PATH_SEPARATOR (podle operačního systému) a DEBUG, který je defaultně na 0 (tedy bez debug výpisů). Při zapnutí DEBUG se dělá hodně logování (při každém callbacku a každém cyklu nekonečné smyčky) a výpisů do konzole, takže rozhodně pro plynulost aplikace nechat na 0.

**Comment by fan1x** [comment]
Jinak, je dobrým zvykem nedávat makra do hlavičkových souborů. Protože všude, kde potom přiložíš daný hlavičkový soubor, tak vložíš i makro...

Proč nejsou konstanty `constexpr`?

**Comment by RadStr** [comment]
Zase mě to nenapadlo :D 
Vzhledem k tomu, že všechny používané konstanty jsou známé už za kompilace, tak změněno.
Makra změnim s dalším commitem.
