### ISSUE TITLE
Používat C++ casting

### ISSUE THREAD

**Issue by fan1x** [RadStr/Music-Keyboard#8]
https://github.com/RadStr/Music-Keyboard/blob/de698d5e6ce9e0bcfe825450fcb83fc38fa86386/Keyboard.cpp#L32

**Comment by RadStr** [comment]
Nahrazeno, hledal jsem to přes regexy, tak snad jsem pokryl všechny.

**Comment by fan1x** [comment]
Co tady: 
https://github.com/RadStr/Music-Keyboard/blob/b5677b0de7d0609152320f5d62da22efb45ad057/Keyboard.cpp#L449

**Comment by RadStr** [comment]
Asi jsem použil nějaký podivný regex, teď jsem to už prošel s tímto \([a-zA-Z_0-9]+\) takže už by tam nic být nemělo.
